/*
 * encoder.c — glue between quadrature.pio and the control loop.
 */
#include "encoder.h"

#include "hardware/pio.h"
#include "pico/stdlib.h"

#include "board_config.h"
#include "control.h"          /* enc_count_delta() - host-pure */
#include "quadrature.pio.h"   /* generated by pico_generate_pio_header() */

#define ENC_PIO   pio0
#define ENC_SM    0u

/* How long to wait for a fresh count before giving up. The state machine
 * pushes every ~9 cycles (~60 ns), so this is roughly a thousand times
 * longer than it should ever need. Bounded rather than blocking on purpose:
 * this runs inside the 10 ms control tick, and a hang here would take the
 * failsafe down with it. */
#define ENC_READ_TIMEOUT_US 200u

static bool     s_ready;
static int32_t  s_last;
static int32_t  s_offset;
static volatile uint32_t s_stalls;   /* written in the ISR, read by main() */

bool encoder_init(void)
{
    s_ready = false;
    s_last = 0;
    s_offset = 0;
    s_stalls = 0;

    /* Ask before taking. pio_sm_claim() PANICS on an already-claimed state
     * machine, and encoder.h promises this function returns false instead -
     * a panic here would take the failsafe down with it. */
    if (pio_sm_is_claimed(ENC_PIO, ENC_SM)) {
        return false;
    }
    if (!pio_can_add_program(ENC_PIO, &quadrature_program)) {
        return false;
    }
    uint offset = pio_add_program(ENC_PIO, &quadrature_program);

    /* quadrature.pio declares .origin 0, so this is 0 by construction; the
     * helper asserts it too. Kept explicit because the jump table depends on
     * it and a future second PIO program in this block would break it. */
    pio_sm_claim(ENC_PIO, ENC_SM);
    quadrature_program_init(ENC_PIO, ENC_SM, offset, PIN_ENC_A);

    s_ready = true;
    return true;
}

int32_t encoder_get_count(void)
{
    if (!s_ready) {
        /* The decoder never loaded, so there is no feedback at all. Count it
         * as a stall: that is exactly what the STALL diagnostic means ("the
         * control loop is running on feedback that is not real"), and it makes
         * the condition visible on the wire to someone who connected after the
         * boot-time ERR line scrolled past. control_tick() separately refuses
         * to close the loop in this state. */
        s_stalls++;
        return 0;
    }

    /*
     * The state machine pushes the running count continuously with
     * `push noblock`, so the RX FIFO holds up to four values of unknown age.
     * Draining (level + 1) of them guarantees the LAST one read was pushed
     * after this function started, i.e. it is fresh rather than stale.
     * That +1 is the whole trick.
     */
    uint32_t n = (uint32_t)pio_sm_get_rx_fifo_level(ENC_PIO, ENC_SM) + 1u;
    uint32_t raw = (uint32_t)s_last;
    uint32_t deadline = time_us_32() + ENC_READ_TIMEOUT_US;
    bool got = false;

    while (n > 0u) {
        if (pio_sm_is_rx_fifo_empty(ENC_PIO, ENC_SM)) {
            /* time_us_32() wraps every ~71 minutes; the subtraction makes the
             * comparison wrap-safe where a plain `now > deadline` would not. */
            if ((int32_t)(time_us_32() - deadline) >= 0) {
                s_stalls++;
                break;
            }
            continue;
        }
        raw = pio_sm_get(ENC_PIO, ENC_SM);
        got = true;
        n--;
    }

    if (got) {
        s_last = (int32_t)raw;
    }
    /* enc_count_delta(), not `s_last - s_offset`. Both are free-running 32-bit
     * counters, so a plain signed subtraction is signed overflow - undefined
     * behaviour - once they straddle the wrap. That is the exact bug
     * enc_count_delta() exists to avoid (see control.h); using it here too
     * means there is one wrapping-subtract idiom in the firmware, not two. */
    return enc_count_delta(s_last, s_offset);
}

void encoder_zero(void)
{
    s_offset = s_last;
}

uint32_t encoder_stall_count(void)
{
    return s_stalls;
}
